### ISSUE TITLE
amsterdam install not works on Ubuntu desktop 18.04 64 bit

### ISSUE THREAD

**Issue by michal25** [StamusNetworks/Amsterdam#58]
# pip install amsterdam
Collecting amsterdam
  Using cached https://files.pythonhosted.org/packages/ac/f2/13c4dab827cd19271aca2786d712ba203da276d09d96804b3bcdcf36613a/amsterdam-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-62cdWj/amsterdam/setup.py", line 3, in <module>
        from src.amsterdam import AMSTERDAM_VERSION
      File "src/__init__.py", line 2, in <module>
        from .amsterdam import *
      File "src/amsterdam.py", line 28, in <module>
        from docker import Client
    ImportError: cannot import name Client
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-62cdWj/amsterdam/

**Comment by pevma** [comment]
I think Amsterdam needs an overhaul.
CC @regit

**Comment by saneysrikanth** [comment]
sudo apt-get install docker.io python-pip
pip install docker-compose==1.9.0
sudo pip install amsterdam

Try the above steps @michal25
